dubbo:
  application:
    name: sso-web
  registry:
    protocol: zookeeper
    address: 120.27.240.138:2181
  protocol:
    port: 28813
spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: 114.55.100.63
    port: 5672
    username: xb
    password: 123
    virtual-host: /xb
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 120.27.240.138:22122

image:
  server: http://120.27.240.138/
server:
  port: 8086
